"""00002

Revision ID: ef2da5dc1f46
Revises: 76164ffac5d3
Create Date: 2023-02-25 16:38:41.108187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2da5dc1f46'
down_revision = '76164ffac5d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_buyers_email'), 'buyers', ['email'], unique=False)
    op.create_index(op.f('ix_sellers_email'), 'sellers', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_email'), table_name='sellers')
    op.drop_index(op.f('ix_buyers_email'), table_name='buyers')
    # ### end Alembic commands ###
