"""00003

Revision ID: 05184080de84
Revises: ef2da5dc1f46
Create Date: 2023-02-25 16:39:44.036785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05184080de84'
down_revision = 'ef2da5dc1f46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    # ### end Alembic commands ###
